substitutions: {_REGION: asia-south1, _REPOSITORY: question-bank, _SERVICE: question-bank-cloud-v4}
steps:
- name: gcr.io/cloud-builders/docker
  args: [build, -t, '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/cloud-v4:$COMMIT_SHA', .]
- name: gcr.io/cloud-builders/docker
  args: [push, '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/cloud-v4:$COMMIT_SHA']
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args: [run, services, update, '${_SERVICE}', --region, '${_REGION}', --image, '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/cloud-v4:$COMMIT_SHA']
images: ['${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/cloud-v4:$COMMIT_SHA']
