SCHEMA = '''
CREATE TABLE IF NOT EXISTS enquiries (
 id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, email TEXT NOT NULL, phone TEXT NOT NULL,
 interest TEXT NOT NULL, message TEXT NOT NULL, source TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'NEW',
 admin_notes TEXT NOT NULL DEFAULT '', created_at REAL NOT NULL, updated_at REAL NOT NULL);
CREATE TABLE IF NOT EXISTS enquiry_challenges (
 id TEXT PRIMARY KEY, answer_hash TEXT NOT NULL, expires_at REAL NOT NULL, used INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS engagement_limits (key TEXT PRIMARY KEY, window_start REAL NOT NULL, calls INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS flag_trials (user_id INTEGER PRIMARY KEY REFERENCES users(id), started_at REAL NOT NULL, expires_at REAL NOT NULL);
'''
